export const SETTINGS_KEY_ADD_LOCATION_NAME = 'ADD_LOCATION_NAME';
export const SETTINGS_KEY_ADD_LOCATION_LATITUDE = 'ADD_LOCATION_LATITUDE';
export const SETTINGS_KEY_ADD_LOCATION_LONGITUDE = 'ADD_LOCATION_LONGITUDE';
export const SETTINGS_KEY_ADD_LOCATION_DETAILS = 'ADD_LOCATION_DETAILS';
